### PR TITLE
Add CF2-Group proposal

### PR DESCRIPTION
**Pull request by czender**
This ~2 year-old letter to the CF group contains my thoughts on how to incorporate extended data model groups into CF2. It can serve as a basis for drafting. Need to be converted to ASCiiDoc...

### CODE REVIEW

**Comment by czender** [comment]
Once someone merges this we should add the comments from the Google doc to the AsciiDoc as issues.

**Comment by czender** [comment]
@ethanrd Please give me write access to this repo ASAP

**Comment by erget** [comment]
@ethanrd I'll be migrating the comments and contributing to the proposals here as well, could I also have write access?

**Comment by ethanrd** [comment]
@czender and @erget For repos in the Unidata GitHub organization, we generally only give write permission to a few Unidata folks and otherwise encourage the use of PRs for making changes. (Several Unidata projects use PRs even for the Unidata folks with write permission, which is nice for having reviews on all PRs.)

Though it can require a change in workflow, this model has worked quite well so far. 

I can double check if we can stretch this policy for close collaborators. But PRs are definitely our preference.

**Comment by erget** [comment]
I agree with this policy and would prefer to work by PR in any case. The only reason I would like to have write access would be so that I can manipulate issues more easily within the repository - that way we have them managed centrally on "neutral ground", rather than in some user's repository. Independent of that though I plan to work by PR so we can review changes in a more granular fashion.

**Comment by dopplershift** [comment]
@ethanrd It suddenly occurs to me that (I think) we could achieve that workflow by enabling write access, but requiring a review from a code owner—which we could define more narrowly.

**Comment by ethanrd** [comment]
@dopplershift That would be great if it works. Can you require code review for a repo or only on a branch by branch basis?

**Comment by czender** [comment]
Thank you for your help @ethanrd and @dopplershift. However, I expect rapid community feedback for this proposal once it is posted to CF in the next week or so. The rules/permissions governing this GitHub repository do permit the level of responsiveness I think is needed. So we intend to move the CF2-Group proposal to the GitHub diwg/cf2 repository in the next few days. I will update this thread with more info. at that time.

**Comment by dopplershift** [comment]
@ethanrd It's set up now. You should be able to give other collaborators write access. No PR can be merged without a review from a code owner, which right now is only you.

@czender As someone who lives on GitHub on a daily basis, I would have thought the feedback process would have been:

1. Make a PR with updates/proposed text
2. People comment, suggest edits
3. Author makes changes, updates PR (go to 2)
4. Once done, PR is merged by someone with authority

Honestly, GitHub has nothing to do with throughput here, only the parties involved. So if that's the problem, blame your collaborators, not the venue. 😁 But as someone not involved in the proposal I don't actually have a horse in the race.

**Comment by czender** [comment]
@dopplershift your proposed workflow is fine, however, there is a bottleneck at step 4 because the authors lack sufficient permissions. The CF2-Group document authors (@erget and I, so far) need full write access to its repository, including the ability to grant full access to others, merge, create labels, dispose of issues, etc. Do we have that in EC-netCDF-CF now or can we have it by Monday?

**Comment by czender** [comment]
@dopplershift and @ethanrd we have migrated CF2-Group to [here](http://github.com/diwg/cf2). I just submitted a PR to remove it from EC-netCDF-CF to reduce confusion.

**Pull request merged**
